apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-queue.fullname" . }}-config
  labels:
    {{- include "order-queue.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  PORT: {{ .Values.env.PORT | quote }}