apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order-queue.fullname" . }}
  labels:
    {{- include "order-queue.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "order-queue.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "order-queue.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.env.PORT }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "order-queue.fullname" . }}-config
          env:
            - name: DB_HOST
              value: {{ include "order-queue.fullname" . }}-postgresql
            - name: DB_PORT
              value: "{{ .Values.postgresql.service.ports.postgresql }}"
            - name: DB_USERNAME
              value: {{ .Values.postgresql.auth.username }}
            - name: DB_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: DB_NAME
              value: {{ .Values.postgresql.auth.database }}
            - name: RABBITMQ_URL
              value: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ include "order-queue.fullname" . }}-rabbitmq:{{ .Values.rabbitmq.service.ports.amqp }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}