apiVersion: v2
name: order-queue
description: A Helm chart for the Order Queue service
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: ~16.7.11
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: rabbitmq
    version: ~16.0.7
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled