replicaCount: 1

image:
  repository: order-queue
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

app:
  port: 3000

rabbitmq:
  enabled: true
  auth:
    username: guest
    password: guest
  service:
    port: 5672

postgresql:
  enabled: true
  auth:
    username: "dbUser"
    password: "12345"
    database: "orders"
  primary:
    persistence:
      enabled: true
      size: 5Gi