replicaCount: 1

image:
  repository: ghcr.io/sebdevar/order-queue
  pullPolicy: IfNotPresent
  tag: "1.0.0"

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

env:
  NODE_ENV: production
  PORT: 3000
  NOTIFICATION_URL: http://ptsv3.com/t/order-queue/post

postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: orderqueue
  service:
    ports:
      postgresql: 5432

rabbitmq:
  enabled: true
  auth:
    username: user
    password: password
  service:
    ports:
      amqp: 5672
